### ISSUE TITLE
All metrics are 0 while training (except loss)

### ISSUE THREAD

**Issue by Arkkienkeli** [funalab/QCANet#2]
Hello, I did run the following command for training for the dataset you provided as an example:
```
python train_ndn.py -i ../datasets/ --opt_method Adam -g 0
```
During training all metrics (precision, recall, F) were 0.

**Comment by tokkuman** [comment]
Since the evaluation metrics (precision, recall, and F-measure) is calculated using recursive processing, it takes time to calculate at the initial stage of learning.
Therefore, NDN does not calculate these metrics in the initial learning phase (up to epoch 20) and return 0.
Of course, since the loss is calculated, NDN is learning.

I'm sorry that I have not written this description in README.
